todo/accounts/urls.py
from django.urls import path

from accounts.views import login_view, \
    logout_view, \
    register_view, \
    RegisterView, \
    UserAdd, \
    UserDetailView, \
    ProfilesList, \
    UserChangeView,\
    UserChangePassword

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('create/', RegisterView.as_view(), name='create'),
    path('add/user/<int:pk>/',UserAdd.as_view(),name='add-user'),
    path('user/deteil/<int:pk>',UserDetailView.as_view(),name='user-detail'),
    path('profiles/',ProfilesList.as_view(),name='profile'),
    path('profile/update/',UserChangeView.as_view(),name='profile-update'),
    path('profile/change-password/',UserChangePassword.as_view(),name='change-password')

]

todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from webapp.views import *


urlpatterns = [
    path('admin/',  admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('accounts/',include('accounts.urls')),
    path('', RedirectView.as_view(url='webapp/', permanent=False))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/webapp/urls.py
from django.urls import path
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
path('task/<int:pk>', TaskView.as_view(), name='task_view'),
path('add/<int:pk>', AddView.as_view(), name='add_view'),
path('update/<int:pk>', UpdateViewList.as_view(), name='update_view'),
path('remove/<int:pk>', RemoveView.as_view(), name='remove_view'),
path('', ProjectListView.as_view(), name='home'),
path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
path('create/', ProjectCreateView.as_view(), name='create'),
path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete_project'),
path('update/project/<int:pk>',ProjectUpdateView.as_view(),name='project_update')
]

todo/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User,Group
from .Validator import TaskCreateForm, MinLengthValidator

b = ['@', "$", '!', '#', '%', '^', '*', '~']


class Project(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    desc = models.TextField(max_length=200, verbose_name='Описание')
    users = models.ManyToManyField('auth.User', blank=True, related_name='users', verbose_name='Пользователь')
    begin_date = models.DateField('date')
    expiration_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.title, self.desc)

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        permissions = [
            ('add_delete_user', 'Добавление и удаление пользователя')
        ]


class Task(models.Model):
    id = models.AutoField(primary_key=True)
    summary = models.CharField(max_length=100, validators=(MinLengthValidator(5),))
    status = models.ForeignKey('Status', on_delete=models.PROTECT, verbose_name='Статус', null=True)
    types = models.ManyToManyField('Type', blank=True, related_name='types')
    description = models.CharField(max_length=200, validators=(TaskCreateForm(b),))
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    project = models.ForeignKey('Project',
                                on_delete=models.CASCADE,
                                null=True,
                                verbose_name='Проект',
                                related_name='tasks',
                                default=1)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.summary, self.description)

    def get_absolute_url(self):
        return reverse('task', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class Status(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False, blank=False)
    value = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.title, self.value)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Type(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False, blank=False)
    value = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return '{}: {}'.format(self.id, self.title, self.value)

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'

todo/webapp/forms.py
from django import forms

from webapp.models import Task, Project


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('summary', 'description', 'status', 'types')
        widgets = {'types': forms.SelectMultiple(attrs={'class': 'checkbox form-control'}),
                   'description': forms.Textarea(attrs={'cols': 50, 'rows': 10})
                   }


class DateInput(forms.DateInput):
    input_type = 'date'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'desc', 'begin_date', 'expiration_date')
        widgets = {
            'begin_date': DateInput(),
            'expiration_date': DateInput()
        }


class ProjectUserForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('users',)
        widgets = {'users': forms.SelectMultiple(attrs={'class': 'checkbox form-control'}),}

todo/webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView

from webapp.forms import TaskForm, ProjectForm
from webapp.models import Task, Project


class ProjectListView(ListView):
    model = Project
    template_name = 'project/home.html'
    queryset = Project.objects.all()
    paginate_by = 3
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        projects = Project.objects.all()

        paginator = Paginator(projects, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            projects_pages = paginator.page(page)
        except PageNotAnInteger:
            projects_pages = paginator.page(1)
        except EmptyPage:
            projects_pages = paginator.page(paginator.num_pages)

        context['lists_pages'] = projects_pages
        return context


class ProjectDetailView(DetailView):
    template_name = 'project/detail_project.html'
    model = Project
    context_object_name = 'project'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        project = Project.objects.get(id=self.kwargs.get('pk'))
        project_task = project.tasks.all()
        page = self.request.GET.get('page')

        query = self.request.GET.get('q', None)
        if query is not None:
            project_task = project_task.filter(
                Q(summary__icontains=query) |
                Q(description__icontains=query)
            )

        paginator = Paginator(project_task, 5)

        try:
            tasks_pages = paginator.page(page)
        except PageNotAnInteger:
            tasks_pages = paginator.page(1)
        except EmptyPage:
            tasks_pages = paginator.page(paginator.num_pages)

        context['lists_pages'] = tasks_pages
        context['project'] = project
        context['is_paginated'] = True
        return context


class ProjectCreateView(PermissionRequiredMixin,CreateView):
    form_class = ProjectForm
    template_name = 'project/create_project.html'
    queryset = Project.objects.all()
    success_url = reverse_lazy('webapp:home')
    permission_required = ('webapp.add_project',)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/update.html'
    form_class = ProjectForm
    context_object_name = 'project'
    permission_required = 'webapp.change_project'

    def get_success_url(self):
        return reverse('webapp:home')


class ProjectDeleteView(PermissionRequiredMixin,DeleteView):
    model = Project
    permission_required = ('webapp.delete_project',)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:home')


class TaskView(DetailView):
    model = Task
    template_name = 'task/task_template.html'


class AddView(PermissionRequiredMixin,CreateView):
    form_class = TaskForm
    template_name = 'task/task_add_view.html'
    queryset = Task.objects.all()
    permission_required = ('webapp.add_task',)

    def form_valid(self, form):
        print(form.cleaned_data)
        task = form.save(commit=False)
        task.project = get_object_or_404(Project, id=self.kwargs.get('pk'))
        task.save()
        form.save_m2m()
        return self.get_success_url()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return redirect('webapp:detail', pk= self.kwargs.get('pk'))

    def has_permission(self):
        return super().has_permission() and self.request.user in Project.objects.get(pk=self.kwargs.get('pk')).users.all()


class UpdateViewList(PermissionRequiredMixin,UpdateView):
    form_class = TaskForm
    template_name = 'task/update_view.html'
    permission_required = ('webapp.change_task',)

    def has_permission(self):
        print(self.request.user)
        return super().has_permission() and self.request.user in self.get_object().project.users.all()

    def get_object(self):
        id_ = self.kwargs.get('pk')
        return get_object_or_404(Task, pk=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:detail', kwargs={'pk': self.object.project_id})


class RemoveView(PermissionRequiredMixin,DeleteView):
    model = Task
    success_url = reverse_lazy('webapp:home')
    permission_required = ('webapp.delete_task',)

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.users.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

todo/webapp/templates/partial/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}guest{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="style">
</head>
<body class="bg">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'webapp:home' %}">Главная страница</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav menu">

            {% if user.is_authenticated %}
               {% block menu_links %}{% endblock %}
               <li class="nav-item active"><a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a></li>
            {% else %}
                <li class="nav-item active"><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}" class="nav-link">Вход</a></li>
                <li class="menu-right"><a href="{% url 'accounts:register' %}?next={{ request.get_full_path }}" class="nav-link">Регистрация</a></li>
            {% endif %}
             {% if perms.accounts.manage_lead %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Профили</a>
                </li>
            {% endif %}

        </ul>
  </div>
</nav>
<div class="container" >
        {% block content %}
        {%endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</body>

</html>

todo/webapp/templates/partial/list_template.html
    {% for instance in  lists_pages%}
        <tr>
          <td>
              <a href="{% url 'webapp:detail' instance.id %}" >{{ instance.title }}</a>
          </td>

          <td>{{ instance.desc }}</td>
          <td>{{ instance.begin_date }}</td>
          <td>{{ instance.expiration_date }}</td>
            <td>
                <button  type="button" class="btn btn-link">
                    {% if perms.webapp.change_project %}
                        <a href="{%  url 'webapp:project_update' instance.id %}">
                            Редактирование проекта
                        </a>
                    {% endif %}
                </button>
                {% if perms.webapp.delete_project %}
                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#removeModal_{{ instance.id }}">
                        Удалить
                    </button>
                {% endif %}
                  <div class="modal fade" id="removeModal_{{ instance.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                  <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Удаление</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                  </div>
                                  <div class="modal-body">
                                        Вы действительно хотите удалить?
                                   </div>
                                  <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                                        <a class="btn btn-danger" href="{% url 'webapp:delete_project' instance.id %}">Да</a>
                                  </div>
                        </div>
                  </div>
            </td>
        </tr>
{% endfor %}

todo/webapp/templates/partial/pagination.html
{% if is_paginated %}
    {%  if lists_pages.object_list.count == 0 %}
        <h3 align="center">No task</h3>
    {% else %}
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item">
                {% if lists_pages.has_previous %}
                    <a class="page-link" href="?page={{ lists_pages.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% endif %}
            </li>
            {% for page in lists_pages.paginator.page_range %}
                <li class="page-item{% if page == lists_pages.page_obj.number %} active {% endif %}">
                    <a class="page-link " href="?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}
            <li class="page-item">
                {% if lists_pages.has_next %}
                    <a class="page-link" href="?page={{ lists_pages.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
          </ul>
        </nav>
    {% endif %}
{% endif %}

todo/webapp/templates/partial/search.html
<form class="form-inline" action="" method="GET">

    <div class="form-group  mt-4 mb-3"  class="text">
        <label for="inputPassword2" class="sr-only">Password</label>
        <input type="text" name="q" class="form-control" id="inputPassword2" placeholder="Text"  >
    </div>
    <button type="submit" class="btn btn-primary mt-4 mb-3 ml-3 ">Search</button>

    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}

</form>