todo/accounts/urls.py
from django.urls import path

from accounts.views import login_view, \
    logout_view, \
    register_view, \
    RegisterView, \
    UserAdd, \
    UserDetailView, \
    ProfilesList, \
    UserChangeView,\
    UserChangePassword

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('create/', RegisterView.as_view(), name='create'),
    path('add/user/<int:pk>/',UserAdd.as_view(),name='add-user'),
    path('user/deteil/<int:pk>',UserDetailView.as_view(),name='user-detail'),
    path('profiles/',ProfilesList.as_view(),name='profile'),
    path('profile/update/',UserChangeView.as_view(),name='profile-update'),
    path('profile/change-password/',UserChangePassword.as_view(),name='change-password')

]

todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from webapp.views import *


urlpatterns = [
    path('admin/',  admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('accounts/',include('accounts.urls')),
    path('', RedirectView.as_view(url='webapp/', permanent=False))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/webapp/urls.py
from django.urls import path
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
path('task/<int:pk>', TaskView.as_view(), name='task_view'),
path('add/<int:pk>', AddView.as_view(), name='add_view'),
path('update/<int:pk>', UpdateViewList.as_view(), name='update_view'),
path('remove/<int:pk>', RemoveView.as_view(), name='remove_view'),
path('', ProjectListView.as_view(), name='home'),
path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
path('create/', ProjectCreateView.as_view(), name='create'),
path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete_project'),
path('update/project/<int:pk>',ProjectUpdateView.as_view(),name='project_update')
]

todo/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User,Group
from .Validator import TaskCreateForm, MinLengthValidator

b = ['@', "$", '!', '#', '%', '^', '*', '~']


class Project(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    desc = models.TextField(max_length=200, verbose_name='Описание')
    users = models.ManyToManyField('auth.User', blank=True, related_name='users', verbose_name='Пользователь')
    begin_date = models.DateField('date')
    expiration_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.title, self.desc)

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        permissions = [
            ('add_delete_user', 'Добавление и удаление пользователя')
        ]


class Task(models.Model):
    id = models.AutoField(primary_key=True)
    summary = models.CharField(max_length=100, validators=(MinLengthValidator(5),))
    status = models.ForeignKey('Status', on_delete=models.PROTECT, verbose_name='Статус', null=True)
    types = models.ManyToManyField('Type', blank=True, related_name='types')
    description = models.CharField(max_length=200, validators=(TaskCreateForm(b),))
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    project = models.ForeignKey('Project',
                                on_delete=models.CASCADE,
                                null=True,
                                verbose_name='Проект',
                                related_name='tasks',
                                default=1)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.summary, self.description)

    def get_absolute_url(self):
        return reverse('task', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class Status(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False, blank=False)
    value = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.title, self.value)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Type(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False, blank=False)
    value = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return '{}: {}'.format(self.id, self.title, self.value)

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'

todo/webapp/forms.py
from django import forms

from webapp.models import Task, Project


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('summary', 'description', 'status', 'types')
        widgets = {'types': forms.SelectMultiple(attrs={'class': 'checkbox form-control'}),
                   'description': forms.Textarea(attrs={'cols': 50, 'rows': 10})
                   }


class DateInput(forms.DateInput):
    input_type = 'date'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'desc', 'begin_date', 'expiration_date')
        widgets = {
            'begin_date': DateInput(),
            'expiration_date': DateInput()
        }


class ProjectUserForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('users',)
        widgets = {'users': forms.SelectMultiple(attrs={'class': 'checkbox form-control'}),}

todo/webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView

from webapp.forms import TaskForm, ProjectForm
from webapp.models import Task, Project


class ProjectListView(ListView):
    model = Project
    template_name = 'project/home.html'
    queryset = Project.objects.all()
    paginate_by = 3
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        projects = Project.objects.all()

        paginator = Paginator(projects, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            projects_pages = paginator.page(page)
        except PageNotAnInteger:
            projects_pages = paginator.page(1)
        except EmptyPage:
            projects_pages = paginator.page(paginator.num_pages)

        context['lists_pages'] = projects_pages
        return context


class ProjectDetailView(DetailView):
    template_name = 'project/detail_project.html'
    model = Project
    context_object_name = 'project'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        project = Project.objects.get(id=self.kwargs.get('pk'))
        project_task = project.tasks.all()
        page = self.request.GET.get('page')

        query = self.request.GET.get('q', None)
        if query is not None:
            project_task = project_task.filter(
                Q(summary__icontains=query) |
                Q(description__icontains=query)
            )

        paginator = Paginator(project_task, 5)

        try:
            tasks_pages = paginator.page(page)
        except PageNotAnInteger:
            tasks_pages = paginator.page(1)
        except EmptyPage:
            tasks_pages = paginator.page(paginator.num_pages)

        context['lists_pages'] = tasks_pages
        context['project'] = project
        context['is_paginated'] = True
        return context


class ProjectCreateView(PermissionRequiredMixin,CreateView):
    form_class = ProjectForm
    template_name = 'project/create_project.html'
    queryset = Project.objects.all()
    success_url = reverse_lazy('webapp:home')
    permission_required = ('webapp.add_project',)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/update.html'
    form_class = ProjectForm
    context_object_name = 'project'
    permission_required = 'webapp.change_project'

    def get_success_url(self):
        return reverse('webapp:home')


class ProjectDeleteView(PermissionRequiredMixin,DeleteView):
    model = Project
    permission_required = ('webapp.delete_project',)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:home')


class TaskView(DetailView):
    model = Task
    template_name = 'task/task_template.html'


class AddView(PermissionRequiredMixin,CreateView):
    form_class = TaskForm
    template_name = 'task/task_add_view.html'
    queryset = Task.objects.all()
    permission_required = ('webapp.add_task',)

    def form_valid(self, form):
        print(form.cleaned_data)
        task = form.save(commit=False)
        task.project = get_object_or_404(Project, id=self.kwargs.get('pk'))
        task.save()
        form.save_m2m()
        return self.get_success_url()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return redirect('webapp:detail', pk= self.kwargs.get('pk'))

    def has_permission(self):
        return super().has_permission() and self.request.user in Project.objects.get(pk=self.kwargs.get('pk')).users.all()


class UpdateViewList(PermissionRequiredMixin,UpdateView):
    form_class = TaskForm
    template_name = 'task/update_view.html'
    permission_required = ('webapp.change_task',)

    def has_permission(self):
        print(self.request.user)
        return super().has_permission() and self.request.user in self.get_object().project.users.all()

    def get_object(self):
        id_ = self.kwargs.get('pk')
        return get_object_or_404(Task, pk=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:detail', kwargs={'pk': self.object.project_id})


class RemoveView(PermissionRequiredMixin,DeleteView):
    model = Task
    success_url = reverse_lazy('webapp:home')
    permission_required = ('webapp.delete_task',)

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.users.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

todo/webapp/templates/project/create_project.html
{% extends 'partial/base.html' %}

{% block content %}

    <h3 align="center" style="margin-top:20px">Добавить новый проект</h3>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {% include "task/task_form.html" with button_text="Добавить" %}
        </div>
    </form>

{%  endblock content %}

todo/webapp/templates/project/detail_project.html
{% extends 'partial/base.html' %}
{% include 'task/tasks_template.html' %}
{% block content %}

    <span>
    {% if perms.webapp.add_task and request.user in project.users.all %}
        <a class="btn btn-success mt-4 mb-3" href="{% url 'webapp:add_view' project.id %}">ДОБАВИТЬ ЗАПИСЬ</a>
    {% endif %}
        {%  include 'partial/search.html' %}
    </span>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Задачи </th>
          <th scope="col">Типы</th>
          <th scope="col">Статус</th>
          <th scope="col">Дата создания</th>
          <th scope="col">Дата обновления</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
            {% for t in lists_pages %}
                <tr>
                  <td><a href="{% url 'webapp:task_view' t.id %}">{{ t.summary }}</a></td>
                  <td>
                      {% for type in t.types.all %}
                          {{ type.title  }}
                          {% if not forloop.last  %}
                              ,
                          {% endif  %}
                      {% endfor %}
                  </td>
                  <td>{{ t.status.title }}</td>
                  <td>{{ t.create_date }}</td>
                  <td>{{ t.update_date }}</td>
                  <td>
                  {% if perms.webapp.change_task and request.user in project.users.all %}
                      <a class="mr-3" href="{% url 'webapp:update_view' t.id %}">Редактировать</a>
                    {% endif %}
                        <button type="button" class="btn btn-link" data-toggle="modal" data-target="#removeModal_">
                            {% if perms.webapp.delete_task and request.user in project.users.all %}
                                <a data-toggle="modal" data-target="#removeModal_{{ t.id }}" href="{% url 'webapp:remove_view' t.id %}">Удалить</a>
                            {% endif %}
                        </button>
                      <div class="modal fade" id="removeModal_{{ t.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                      <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Удаление</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                      </div>
                                      <div class="modal-body">
                                            Вы действительно хотите удалить?
                                       </div>
                                      <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>

                                            <a type="button" class="btn btn-danger" href="{% url 'webapp:remove_view' t.id %}">Да</a>

                                      </div>
                                </div>
                          </div>
                      </div>
                  </td>
                </tr>
            {%  endfor %}
        </tbody>
    </table>
    <hr>
<ul class="list-group mb-3">
  <li class="list-group-item disabled">Пользователи проекта</li>
     {% for u in project.users.all %}
        <li class="list-group-item">
        <a href="{% url 'accounts:user-detail' u.id%}">{{ u.username }}</a>
        </li>
     {% endfor %}
</ul>

<span>
    {% if perms.webapp.add_delete_user and request.user in project.users.all %}
        <a class="btn btn-outline-warning mt-4 mb-3"  href="{% url 'accounts:add-user' project.pk %}">ДОБАВИТЬ ПОЬЗОВАТЕЛЯ</a>
    {% endif %}
</span>

{% include 'partial/pagination.html' %}
{%  endblock content %}

todo/webapp/templates/project/home.html
{% extends 'partial/base.html' %}

{% block content %}
        <span>
        {% if perms.webapp.add_project  %}
            <a class="btn btn-success mt-4 mb-3" href="{% url 'webapp:create' %}">ДОБАВИТЬ ПРОЕКТ</a>
        {% endif %}
        </span>

        <table class="table mt-4">
            <thead class="thead-dark">
                <tr>
                  <th scope="col">Название проекта</th>
                  <th scope="col">Описание</th>
                  <th scope="col">Дата создания</th>
                  <th scope="col">Дата окончания</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% include 'partial/list_template.html' %}
            </tbody>
        </table>

{% include 'partial/pagination.html' %}
{%  endblock content %}

todo/webapp/templates/project/update.html
{% extends 'partial/base.html' %}
{% block content %}

<form action="{% url "webapp:project_update" project.id %}" method="post">
    {% include "task/task_form.html" with button_text="Редактировать проект" %}
</form>
{% endblock content %}

todo/webapp/templates/project/user_project_add.html
{% extends 'partial/base.html' %}

{% block content %}

    <h3 align="center" style="margin-top:20px;margin-bottom: 20px ">Добавить пользователя</h3>
    <form method="post">

        <div class="form-group">
            {% include "task/task_form.html" with button_text="Добавить" %}
        </div>
    </form>

{%  endblock content %}