todo/accounts/urls.py
from django.urls import path

from accounts.views import login_view, \
    logout_view, \
    register_view, \
    RegisterView, \
    UserAdd, \
    UserDetailView, \
    ProfilesList, \
    UserChangeView,\
    UserChangePassword

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('create/', RegisterView.as_view(), name='create'),
    path('add/user/<int:pk>/',UserAdd.as_view(),name='add-user'),
    path('user/deteil/<int:pk>',UserDetailView.as_view(),name='user-detail'),
    path('profiles/',ProfilesList.as_view(),name='profile'),
    path('profile/update/',UserChangeView.as_view(),name='profile-update'),
    path('profile/change-password/',UserChangePassword.as_view(),name='change-password')

]

todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from webapp.views import *


urlpatterns = [
    path('admin/',  admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('accounts/',include('accounts.urls')),
    path('', RedirectView.as_view(url='webapp/', permanent=False))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/webapp/urls.py
from django.urls import path
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
path('task/<int:pk>', TaskView.as_view(), name='task_view'),
path('add/<int:pk>', AddView.as_view(), name='add_view'),
path('update/<int:pk>', UpdateViewList.as_view(), name='update_view'),
path('remove/<int:pk>', RemoveView.as_view(), name='remove_view'),
path('', ProjectListView.as_view(), name='home'),
path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
path('create/', ProjectCreateView.as_view(), name='create'),
path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete_project'),
path('update/project/<int:pk>',ProjectUpdateView.as_view(),name='project_update')
]

todo/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name='Профиль пользователя',
        related_name='profile',
    )
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True, verbose_name='Аватар')
    about_me = models.CharField(max_length=300, blank=True, null=True)
    links = models.URLField(max_length=200,blank=True, null=True)

    def __str__(self):
        return '{}: {}'.format(self.user,self.avatar, self.about_me, self.links)

    class Meta:
        db_table = 'profiles'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [
            ('manage_lead', 'Просмотр профилей')
        ]

todo/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from django.contrib.auth.models import User

from accounts.models import Profile


class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Password", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Password Confirm", required=True, widget=forms.PasswordInput, strip=False)

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        last_name = cleaned_data.get('last_name')
        first_name = cleaned_data.get('first_name')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        if len(last_name) == 0 and len(first_name) == 0:
            raise forms.ValidationError('Заполните хотя б одну из полей first или last name')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user','avatar', 'about_me', 'links']
        widgets = {
            'about_me': forms.Textarea(attrs={'cols': 50, 'rows': 10})
        }


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(required=True,label='Старый пароль')
    new_password = forms.CharField(required=True,label='Новый пароль')
    password_confirm = forms.CharField(required=True,label='Подтверждение пароля')

    class Meta:
        model = get_user_model()
        fields = ['new_password', 'password_confirm', 'old_password']

    def clean_password_confirm(self):
        new_password = self.cleaned_data.get("new_password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if new_password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return new_password

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('new_password'))
        if commit:
            user.save()
        return user

todo/accounts/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash

from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileUpdateForm, PasswordChangeForm
from accounts.models import Profile
from webapp.forms import ProjectUserForm
from webapp.models import Project
from django.views.generic import DetailView

from django.contrib.auth import get_user_model


from django.core.paginator import Paginator



def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('webapp:home')
        else:
            context['has_error'] = True
    return render(request, 'accounts/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:home')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            return redirect('webapp:home')
    else:
        form = MyUserCreationForm()

    return render(request, 'accounts/user_create.html', context={'form': form})


class RegisterView(CreateView):
    model = User
    template_name = 'accounts/user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        print(next_url)
        if not next_url:
            next_url = self.request.POST.get('next')
            print(next_url)
        if not next_url:
            next_url = reverse('webapp:home')
            print(next_url)
        return next_url


class UserAdd(PermissionRequiredMixin,UpdateView):
    model = Project
    template_name = 'project/user_project_add.html'
    form_class = ProjectUserForm
    context_object_name = 'user'
    permission_required = ('webapp.add_delete_user',)

    def get_success_url(self):
        return reverse('webapp:home')

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().users.all()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'accounts/user_detail.html'
    context_object_name = 'user_object'
    paginate_related_by = 3
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        projects = self.get_object().users.all()
        paginator = Paginator(projects, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['lists_pages'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class ProfilesList(PermissionRequiredMixin,ListView):
    model = get_user_model()
    template_name = 'accounts/profile_list.html'
    context_object_name = 'profiles'
    paginate_related_by = 3
    paginate_related_orphans = 0
    permission_required = ('accounts.manage_lead',)


class UserChangeView(LoginRequiredMixin,UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'accounts/user_update.html'
    context_object_name = 'user_object'
    profile_form_class = ProfileUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super(UserChangeView, self).get_context_data(**kwargs)
        context['profile_form'] = kwargs.get('profile_form')
        if context['profile_form'] is None:
            context['profile_form'] = self.get_profile_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        user_form = self.get_form()
        profile_form = self.get_profile_form()

        if user_form.is_valid() and profile_form.is_valid():
            return self.form_valid(user_form, profile_form)
        return self.form_invalid(user_form, profile_form)

    def form_valid(self, user_form, profile_form):
        response = super().form_valid(user_form)
        profile_form.save()
        return response

    def form_invalid(self, user_form, profile_form):
        context = self.get_context_data(form=user_form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return self.profile_form_class(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:user-detail', kwargs={'pk': self.object.pk})


class UserChangePassword(UpdateView):
    model = get_user_model()
    template_name = 'accounts/user_change_pasword.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_object'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        response = super(UserChangePassword, self).form_valid(form)
        update_session_auth_hash(self.request, self.request.user)
        return response

    def get_success_url(self):
        return reverse('accounts:user-detail', kwargs={'pk': self.object.pk})

todo/accounts/templates/accounts/login.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"
      xmlns="http://www.w3.org/1999/html">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords"
          content="unique login form,leamug login form,boostrap login form,responsive login form,free css html login form,download login form">

    <meta name="author" content="leamug">
    <title>Unique Login Form | Bootstrap Templates</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="style">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    </head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-4 text-center">
            <h4>
                <a href="{% url 'accounts:register' %}?next={{ request.GET.next }}">
                    <h4>Register</h4>
                </a>
            </h4>
            <h1 class='text-white'>Unique Login Form</h1>
            <div class="form-login"></br>
                <form action="" method="post" class="text-center">

                    {% csrf_token %}

                    {% if has_error %}

                        <p class="form-error">Неверное имя пользователя или пароль.</p>

                    {% endif %}
                <h4>Secure Login</h4>
                    </br>

                <input type="text" id="userName" class="form-control input-sm chat-input" name="username" placeholder="username"/>
                    </br></br>

                <input type="text" id="userPassword" class="form-control input-sm chat-input" name="password" placeholder="password"/>
                    </br></br>

                <div class="wrapper">
                    <span class="group-btn">
                        <button type="submit" class="btn btn-danger btn-md">login<i class="fa fa-sign-in"></i></button>
                    </span>
               </div>
            </form>
            </div>
        </div>
    </div>
    </br></br>
</div>
<a href="{% url 'webapp:home' %}">
    <h4>Back to HomePage</h4>
</a>
</body>
</html>

todo/accounts/templates/accounts/profile_list.html
{% extends 'partial/base.html' %}
{% block title %}Пользователи{% endblock %}
{% block content %}

    <div class="list-group text-center">
          <h5 class="list-group-item list-group-item-action active">
                Пользователи
          </h5>
            {%  for i in profiles %}
                <a href="{% url 'accounts:user-detail' i.id%}" class="list-group-item list-group-item-action">{{ i.username }}</a>
            {% endfor %}
    </div>

    {% include 'partial/pagination.html' %}

{% endblock %}

todo/accounts/templates/accounts/user_change_pasword.html
{% extends 'partial/base.html' %}

{% block title %}Сменить пароль{% endblock %}
{% block page_header %}Смена пароля{% endblock %}
{% block content %}

<style>
html {
  height: 100%;
}
body {
  margin:0;
  padding:0;
  font-family: sans-serif;
  background: linear-gradient(#141e30, #243b55);
}

.login-box {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 400px;
  padding: 40px;
  transform: translate(-50%, -50%);
  background: rgba(0,0,0,.5);
  box-sizing: border-box;
  box-shadow: 0 15px 25px rgba(0,0,0,.6);
  border-radius: 10px;
}

.login-box h2 {
  margin: 0 0 30px;
  padding: 0;
  color: #fff;
  text-align: center;
}

</style>


<div class="login-box text-center">
  <h2>Смена пароля</h2>
  <form action="" method="POST" enctype="multipart/form-data">
      {% include "task/task_form.html" with button_text="Сохранить" %}
  </form>
</div>


{% endblock %}

todo/accounts/templates/accounts/user_create.html
{% extends 'partial/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1 class="black">Регистрация</h1>

    <form action="{% url 'accounts:create' %}?next={{ request.GET.next }}" method="post">
    {% include 'task/task_form.html' with form_method='post'  button_text="Зарегистрироваться" %}
</form>
{% endblock %}

todo/accounts/templates/accounts/user_detail.html
{% extends 'partial/base.html' %}

{% block title %}Пользователь{% endblock %}
{% block content %}
      {% block menu %}
            {% if user == user_object %}
                <li class="menu_right"><a href="{% url 'accounts:change-password' %}">Сменить пароль</a></li>
                <li class="menu_right"><a href="{% url 'accounts:profile-update' %}">Редактировать профиль</a></li>
            {% endif %}
    {% endblock %}

<div class="body-profile">
    <section class="section about-section gray-bg" id="about">
                <div class="row align-items-center flex-row-reverse">
                    <div class="col-lg-6">
                        <div class="about-text go-to">
                            <h3 class="dark-color">About Me</h3>
                            <p> {{ user_object.profile.about_me }} </p>
                            <div class="row about-list">
                                <div class="col-md-12">
                                    <div class="media">
                                        <label>First Name</label>
                                        <p>{{ user_object.first_name }}</p>
                                    </div>
                                    <div class="media">
                                        <label>Last Name</label>
                                        <p>{{ user_object.last_name }}</p>
                                    </div>
                                    <div class="media">
                                        <label>Email</label>
                                        <p> {{ user_object.email }}</p>
                                    </div>
                                    <div class="media">
                                        <label>link</label>
                                        <a href="{{ user_object.profile.links }}">{{ user_object.profile.links }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-avatar">
                            {% if user_object.profile.avatar %}
                            <img class="avatar" src="{{ user_object.profile.avatar.url }}" alt="user picture">
                            {% endif %}
                        </div>
                    </div>
                </div>
              <div class="counter mt-3">

                  <div class="row ">
                      <div class="col-12 text-center " style="color: #20247b">
                            <h5>Projects</h5>
                        </div>
                  </div>
                    <div class="row">

                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                  <th scope="col">Название проекта</th>
                                  <th scope="col">Описание</th>
                                  <th scope="col">Дата создания</th>
                                  <th scope="col">Дата окончания</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% include 'partial/list_template.html' %}
                            </tbody>
                        </table>
                    </div>
              </div>
    </section>
</div>


{% endblock %}

todo/accounts/templates/accounts/user_update.html
{% extends 'partial/base.html' %}

{% block title %}Редактировать профиль{% endblock %}
{% block page_header %}Редактирование профиля{% endblock %}


{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% include "task/task_form.html" with form=profile_form fields_only=True %}
        {% include "task/task_form.html" with button_text="Сохранить" %}
    </form>

{% endblock %}